-- MySQL Script generated by MySQL Workbench
-- 02/24/16 19:39:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `nickname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `publisher` VARCHAR(255) NULL,
  `status` VARCHAR(255) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idBook`, `User_idUser`),
  UNIQUE INDEX `idBook_UNIQUE` (`idBook` ASC),
  INDEX `fk_Book_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Book_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `library`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Test` (
  `idTest` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`idTest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`testbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`testbook` (
  `idtestbook` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `Test_idTest` INT NOT NULL,
  PRIMARY KEY (`idtestbook`, `Test_idTest`),
  UNIQUE INDEX `idtestbook_UNIQUE` (`idtestbook` ASC),
  INDEX `fk_testbook_Test1_idx` (`Test_idTest` ASC),
  CONSTRAINT `fk_testbook_Test1`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `library`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
